import forms from '@tailwindcss/forms';

/**
 * Industrial Elite design system.
 * Tokens ported from docs/landing-page/industrial_elite/DESIGN.md and the
 * reference mockups in docs/landing-page/*.
 *
 * @type {import('tailwindcss').Config}
 */
export default {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
        './app/**/*.php',
    ],
    theme: {
        extend: {
            colors: {
                'secondary-fixed': '#ffdea5',
                'tertiary-container': '#6e6d6d',
                'primary-container': '#d71920',
                'on-secondary-fixed-variant': '#5d4201',
                'secondary-fixed-dim': '#e9c176',
                secondary: '#e9c176',
                'on-surface': '#e5e2e1',
                'on-tertiary-fixed-variant': '#474746',
                'on-primary': '#690006',
                outline: '#ad8884',
                'surface-dim': '#131313',
                surface: '#131313',
                'on-secondary-container': '#dab36a',
                'inverse-surface': '#e5e2e1',
                'on-surface-variant': '#e6bdb8',
                'on-secondary-fixed': '#261900',
                'surface-tint': '#ffb4ab',
                'on-primary-fixed': '#410002',
                'on-secondary': '#412d00',
                'on-primary-fixed-variant': '#93000d',
                tertiary: '#c8c6c5',
                'on-background': '#e5e2e1',
                'on-error-container': '#ffdad6',
                'surface-container-high': '#2a2a2a',
                'surface-bright': '#3a3939',
                'on-tertiary-fixed': '#1c1b1b',
                primary: '#ffb4ab',
                'on-tertiary': '#313030',
                'primary-fixed': '#ffdad6',
                'on-tertiary-container': '#f3f0ef',
                'surface-container-low': '#1c1b1b',
                error: '#ffb4ab',
                'primary-fixed-dim': '#ffb4ab',
                'on-primary-container': '#ffece9',
                'on-error': '#690005',
                'tertiary-fixed-dim': '#c8c6c5',
                'surface-container': '#201f1f',
                'outline-variant': '#5d3f3c',
                'surface-container-lowest': '#0e0e0e',
                'secondary-container': '#604403',
                'inverse-on-surface': '#313030',
                'surface-variant': '#353534',
                'inverse-primary': '#c00014',
                'error-container': '#93000a',
                'tertiary-fixed': '#e5e2e1',
                'surface-container-highest': '#353534',
                background: '#131313',
                'dragon-red': '#d71920',
                'metallic-gold': '#e9c176',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'margin-mobile': '20px',
                gutter: '32px',
                'margin-desktop': '64px',
                'container-max': '1440px',
                unit: '8px',
            },
            maxWidth: {
                'container-max': '1440px',
            },
            fontFamily: {
                'display-lg': ['"Bodoni Moda"', 'serif'],
                'headline-lg': ['"Bodoni Moda"', 'serif'],
                'headline-md': ['"Bodoni Moda"', 'serif'],
                'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
                'body-md': ['"Hanken Grotesk"', 'sans-serif'],
                'label-caps': ['Geist', 'sans-serif'],
                'mono-data': ['Geist', 'monospace'],
            },
            fontSize: {
                'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'display-lg-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '0em', fontWeight: '600' }],
                'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '0.02em', fontWeight: '500' }],
                'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.15em', fontWeight: '600' }],
                'mono-data': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
            },
        },
    },
    plugins: [forms],
};
